// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4nmTgOwhzUeHHcysR3B9-78a6pciO_QQ',
    appId: '1:45644695582:web:56ebd940b696eb0ea2060f',
    messagingSenderId: '45644695582',
    projectId: 'prm393-fschool',
    authDomain: 'prm393-fschool.firebaseapp.com',
    storageBucket: 'prm393-fschool.firebasestorage.app',
    measurementId: 'G-KJ9Y814YGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyi6ncpmhbu76xjOVsgLIT5xG5kTJsIBU',
    appId: '1:45644695582:android:35f516ed85f280e5a2060f',
    messagingSenderId: '45644695582',
    projectId: 'prm393-fschool',
    storageBucket: 'prm393-fschool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSvxhOJVwMcheWENJyoIB919nvyIFIbYs',
    appId: '1:45644695582:ios:dc4df51d7dd58411a2060f',
    messagingSenderId: '45644695582',
    projectId: 'prm393-fschool',
    storageBucket: 'prm393-fschool.firebasestorage.app',
    iosBundleId: 'com.example.myfschoolse1911',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSvxhOJVwMcheWENJyoIB919nvyIFIbYs',
    appId: '1:45644695582:ios:dc4df51d7dd58411a2060f',
    messagingSenderId: '45644695582',
    projectId: 'prm393-fschool',
    storageBucket: 'prm393-fschool.firebasestorage.app',
    iosBundleId: 'com.example.myfschoolse1911',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4nmTgOwhzUeHHcysR3B9-78a6pciO_QQ',
    appId: '1:45644695582:web:47c1276e9aa05bf0a2060f',
    messagingSenderId: '45644695582',
    projectId: 'prm393-fschool',
    authDomain: 'prm393-fschool.firebaseapp.com',
    storageBucket: 'prm393-fschool.firebasestorage.app',
    measurementId: 'G-6C1YTQTSYK',
  );
}
